server:
  port: 10086
spring:
  application:
    # 服务名称
    name: eureka-server
eureka:
  client:
    service-url:
      # eureka把自己的地址注册到自己上面
      defaultZone: http://127.0.0.1:10086/eureka
    instance:
      # 使用IP地址
      prefer-ip-address: true
      ip-address: 127.0.0.1
