server:
  port: 10086
spring:
  application:
    # 服务名称
    name: eureka-server
eureka:
  client:
    service-url:
      # eureka把自己的地址注册到自己上面,不同的服务
      defaultZone: http://127.0.0.1:10086/eureka
    instance:
      # 使用IP地址
      prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
      ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
