server:
  port: 8088
spring:
  application:
    name: consumer-service
eureka:
  client:
    service-url:
      # 默认注册到这个地址上（注册中心），注册到多个注册中心上，
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
    # 服务消费者每隔5秒从注册中心拉取服务列表，可以方便的调用服务提供者，服务消费者默认拉取服务为true
    registry-fetch-interval-seconds: 5
    instance:
      # 使用IP地址
      prefer-ip-address: true
      ip-address: 127.0.0.1
user-service:
  ribbon:
    # 设置ribbon的默认轮询规则,随机
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms,关键字要正确