server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/yun6
    username: root
    password: root
  application:
    name: user-service
mybatis:
  type-aliases-package: cn.itcast.user.pojo
eureka:
  client:
    service-url:
      # 默认注册到这个地址上
      defaultZone: http://127.0.0.1:10086/eureka
      instance:
        # 使用IP地址
        prefer-ip-address: true
        ip-address: 127.0.0.1